# Generated by Django 3.0.7 on 2021-09-05 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amdin1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admindata',
        ),
    ]
