# Generated by Django 3.0.7 on 2021-09-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amdin1', '0002_delete_admindata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('mobile_number', models.IntegerField(max_length=10)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
    ]
