# Generated by Django 3.0.7 on 2021-09-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amdin1', '0004_auto_20210905_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_register',
            name='mobile_number',
            field=models.CharField(max_length=10),
        ),
    ]
